### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by hrdlnk** [didiercatz/tailwindcss-parcel-boilerplate#5]
Getting the error message below in the console:

```sh
$ npm run dev

> @ dev /private/tmp/tailwind-parcel-test
> npx parcel src/index.html

Server running at http://localhost:1234 
🚨  /private/tmp/tailwind-parcel-test/src/assets/css/style.css:undefined:undefined: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/node_modules/postcss/lib/postcss.js:55:10)
    at module.exports (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/src/transforms/postcss.js:17:19)
    at async CSSAsset.transform (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/src/assets/CSSAsset.js:133:5)
    at async CSSAsset.process (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/src/Asset.js:216:7)
    at async Pipeline.processAsset (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/src/Pipeline.js:46:7)
    at async Pipeline.process (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/src/Pipeline.js:24:23)
    at async Object.run (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Bundler.loadAsset (/private/tmp/tailwind-parcel-test/node_modules/parcel-bundler/src/Bundler.js:577:19)
```

**Comment by livchits** [comment]
Hi, @hrdlnk 

A solution is to unintsall the last versions of tailwind, postcss and autoprefixer after you run `tailwindcss-parcel-boilerplate`:
```
npm uninstall tailwindcss postcss autoprefixer
```
and then install PostCSS 7 and the versions of tailwind and autoprefixer that works with it:

```
npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
```

I created a PR (#6 ) to fix this and you can read more about the issue here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build
